#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# operating system (build VM template)
os: Windows Server 2016
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU
configuration:
  - Release
  - Debug

environment:
  EnableNuGetPackageRestore: true

install:
  - choco install opencover.portable
  # - choco install codecov
  - choco install gitversion -pre -y
  - cmd: dotnet restore src\NClap.sln
  - ps: gitversion /l console /output buildserver
  - ps: appveyor UpdateBuild -Version $env:GitVersion_FullSemVer

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(GitVersion_NuGetVersion)
  package_version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_MajorMinorPatch)
  file_version: $(GitVersion_MajorMinorPatch)
  informational_version: $(GitVersion_InformationalVersion)

build:
  project: src\NClap.sln
  parallel: true
  verbosity: minimal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - ps: OpenCover.Console.exe -oldstyle -register:user "-target:vstest.console.exe" "-targetargs:src\Tests\UnitTests\bin\$env:CONFIGURATION\net461\NClap.Tests.dll /logger:Appveyor" -skipautoprops "-filter:+[NClap]*" -output:coverage_$env:CONFIGURATION.xml

after_test:
  - ps: |
      (New-Object System.Net.WebClient).DownloadFile("https://github.com/codecov/codecov-exe/releases/download/1.0.3/Codecov.zip", (Join-Path $pwd "Codecov.zip")) # Download Codecov.zip from github release.
      Expand-Archive .\Codecov.zip -DestinationPath . # UnZip the file.
  - ps: .\Codecov\codecov.exe -f coverage_$env:CONFIGURATION.xml

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # publish coverage data
  - path: coverage_$(Configuration).xml
    name: CodeCoverage

  # publish NuGet packages
  - path: 'src\NClap\bin\$(Configuration)\*.nupkg'
    name: Packages

  # publish loose binaries (all target frameworks)
  - path: 'src\NClap\bin\$(Configuration)'
    name: Binaries