#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# operating system (build VM template)
os: Windows Server 2016
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build cache to preserve files/folders between builds
cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

#---------------------------------#
#       build configuration       #
#---------------------------------#

# set up environment
environment:
  EnableNuGetPackageRestore: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release
  - Debug

# install a few prereqs
install:
  - choco install opencover.portable
  - choco install codecov
  # - choco install coveralls.net -source https://nuget.org/api/v2/

# restore NuGet packages before building
before_build:
  - nuget restore src\NClap.sln

# build!
build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\NClap.sln          # path to Visual Studio solution or project
  verbosity: minimal              # MSBuild verbosity level

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - ps: OpenCover.Console.exe -oldstyle -register:user "-target:vstest.console.exe" "-targetargs:src\Tests\UnitTests\bin\$env:CONFIGURATION\net462\NClap.Tests.dll /logger:Appveyor" -skipautoprops "-filter:+[NClap]*" -output:coverage_$env:CONFIGURATION.xml
  - ps: codecov -f coverage_$env:CONFIGURATION.xml

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # publish coverage data
  - path: coverage_$(Configuration).xml
    name: CodeCoverageData

  # publish NuGet packages
  - path: 'src\NClap\bin\$(Configuration)\*.nupkg' # find all NuGet packages recursively
    name: NuGetPackages

  # publish loose binaries
  - path: 'src\NClap\bin\$(Configuration)\net461'
    name: BinariesNetFramework

  # publish loose binaries
  - path: 'src\NClap\bin\$(Configuration)\netstandard1.6'
    name: BinariesNetStandard
